meta:
  title: Finzly Connect
  description: Embed pioneering financial services into your innovative platforms using Finzly Connect
  siteUrl: https://api.finzly.io/
  keywords: Finzly, API , BaaS, Payment Hub, Payments, FX, International payments, Foreign Exchange, BankOS, FinzlyOS, open Banking API
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./images/logo.png
  altText: Finzly Connect 
toc:
  enable: true
oasDefinitions:
  paymentApi: ./openapi/paymentApi.yaml
  fxApi: ./openapi/fxApi.yaml
  customerApi: ./openapi/customerApi.yaml
  userApi: ./openapi/userAPI.yaml
  paymentWebhookApi: ./openapi/paymentWebhookApi.yaml
  depositAccountApi: ./openapi/depositAccountApi.yaml

# postBodyScripts:
scripts:
  - ./css/custom.js
  # add links to definitions in our API registry by using a fully qualified URL.

stylesheets:
  - ./css/style.css
  - ./css/custom.css
  - ./css/bootstrap.min.css
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap
  - https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap

#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  - label: API Docs
    page: developer-portal/index.md

  - label: Finzly.com
    icon: ./images/logo.png
    href: https://finzly.com/


footer:
  copyrightText: Copyright © Finzly 2022-2023. All right reserved.
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          target: '_blank'
          href: 'https://finzly.com/terms'
         
        - label: Privacy Notice
          target: '_blank'
          href: 'https://finzly.com/privacy'
        - label: Security
          target: '_blank'
          href: 'https://finzly.com/finzly-security-page'
    - group: Support
      items:
        - label: About
          target: '_blank'
          href: https://finzly.com/about
        - label: Contact us
          target: '_blank'
          href: https://finzly.com/contact/
